### PR TITLE
schedule dencun on goerli

### PR DESCRIPTION
**Pull request by g11tech**
see: 
 - https://github.com/ethereum/EIPs/pull/8051

### CODE REVIEW

**Review by philknows — APPROVED** [review]

**Comment by etan-status** [comment]
Proposing to make this repo the canonical one (over eth2-networks repo). Here a PR that makes this loadable from Nimbus (we need the block hash file):

- https://github.com/eth-clients/goerli/pull/179

**Comment by rolfyone** [comment]
I could be wrong, but when i loaded it to teku we were missing all the deneb config:

```
# Deneb
# `2**7` (=128)
MAX_REQUEST_BLOCKS_DENEB: 128
# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK
MAX_REQUEST_BLOB_SIDECARS: 768
# `2**12` (= 4096 epochs, ~18 days)
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
# `6`
BLOB_SIDECAR_SUBNET_COUNT: 6
# `uint64(6)`
MAX_BLOBS_PER_BLOCK: 6
```

and the validator cycle change:

```
# [New in Deneb:EIP7514] 2**3 (= 8)
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8
```
Is everyone else getting these fields from elsewhere?

**Comment by etan-status** [comment]
The fields are initialized from the `mainnet` preset (the config refers to the preset to load defaults from at the start)

**Comment by g11tech** [comment]
@rolfyone  yea we generally keep adding fields to our mainnet `config` and any provided `config` overrides the `mainnet` fields,  @etan-status  these fields  (https://github.com/ethereum/consensus-specs/blob/dev/configs/mainnet.yaml#L144) are separate from the preset (https://github.com/ethereum/consensus-specs/blob/dev/presets/mainnet/deneb.yaml) so i guess they should be added here

@parithosh what is the strategy for generating and keep the configs for testnets? all fields are generated and maintained or only those which are overriden?

**Comment by parithosh** [comment]
Newer testnets are all generated from here: https://github.com/ethpandaops/ethereum-genesis-generator/blob/master/config-example/cl/config.yaml

The older ones like goerli are just manually updated, so we try to keep it up to date with: https://github.com/ethereum/consensus-specs/blob/dev/configs/mainnet.yaml . Its extremely likely that the last time we updated it was during the withdrawals fork

**Review by parithosh — APPROVED** [review]

**Review by barnabasbusa — APPROVED** [review]

**Comment by rolfyone** [comment]
LGTM!

**Review by rolfyone — APPROVED** [review]

**Review by pk910 — APPROVED** [review]

**Pull request merged**
